#                                                          Made by Ganesh

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hand1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import handmain
def hii():
    handmain.run()
    return 

class Ui_HandGestures(object):
    def setupUi(self, HandGestures):
        HandGestures.setObjectName("HandGestures")
        HandGestures.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(HandGestures)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 0, 591, 281))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 50, 611, 341))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(300, 320, 171, 71))
        self.pushButton.clicked.connect(hii)
        self.pushButton.setObjectName("pushButton")
        HandGestures.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(HandGestures)
        self.statusbar.setObjectName("statusbar")
        HandGestures.setStatusBar(self.statusbar)

        self.retranslateUi(HandGestures)
        QtCore.QMetaObject.connectSlotsByName(HandGestures)
    
    def retranslateUi(self, HandGestures):
        _translate = QtCore.QCoreApplication.translate
        HandGestures.setWindowTitle(_translate("HandGestures", "HandGestures"))
        self.label.setText(_translate("HandGestures", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">This tool helps to adjust volume using hand gestures</span></p></body></html>"))
        self.label_2.setText(_translate("HandGestures", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">If we expand index finger and thumb then volume increases </span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">if we compress index finger and thumb then volume decreases</span></p></body></html>"))
        self.pushButton.setText(_translate("HandGestures", "START"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HandGestures = QtWidgets.QMainWindow()
    ui = Ui_HandGestures()
    ui.setupUi(HandGestures)
    HandGestures.show()
    sys.exit(app.exec_())
#                                                          Made by Ganesh